version: '3'             #version
services:
  mongodb:               #containername
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb



#To run docker compose file == sudo docker-compose -f file_name up
#To run docker compose file == sudo docker-compose -f file_name down

# version: '2'
# services:
#   web:
#     build:
#       context: ''
#       dockerfile: Dockerfile
#     ports:
#      - "3010:3010"